### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by kwizl**
# Final Corrections
The final corrections include:

- Added News Conversation Section

- Added stickler yml file

- Made the Menu Responsive with a dropdown

- Made the webpage responsive using Bootstrap grid

- Rectified stylesheet errors using linter

### CODE REVIEW

**Comment by pelzolga123** [comment]
### Hi Martin, I am marking this pull request as invalid due to following reasons:

1. Pull request should have meaningful name and brief description of what you did in this project. [Link to pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

2. Your project is missing .stickler.yml file.

### Please kindly fix listed issues and submit for review once more.
If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by pelzolga123** [comment]
### You fixed first issue, but still this project requires .stickler.yml file. Right now it is absent.  
### Please add linter file and submit for review once more.

**Comment by mosesogwo** [comment]
**You have added .stickler.yml file but you have not turned on stickler for this repo**
Please follow this link [](https://github.com/apps/stickler-ci) to turn on stickler for this repository.
For full instructions on setting up stickler, check this link: https://github.com/microverseinc/linters-config/tree/master/css

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi @kwizl, :clap: good work. We have some required changes to be made before approval:

1. Adjust the font of this title to match the original.

image

2. On medium screens, align the text in the two sections below to look like the original:

image

3. The following sections are not properly aligned on medium screen sizes. Compare them with the original and ensure that they match:

image

image

image

image

image

3. On small screens, align the social media icons to match the original.

4. The package-lock.json file is not needed in this project.

5. You have many css styles that could be applied using bootstrap classes. Use bootstrap classes everywhere possible.



**Please make the requested adjustments and submit another code review request.**

### Status: Changes requested.

**Comment by rOluochKe** [comment]
@kwizl That was a job, as mentioned by my previous colleagues. You have made all the changes required. Your project is approved.  

You can move to the next project, best of luck

**Pull request merged**
